# log = true
[general]
program_name = "CSI"
program_desc = "This is the description of my cool program!"
source_dir = "~/my_program_src/"


[[pages]]
Welcome = { title = "Welcome title", desc = "Welcome to my cool program installer."}
[[pages]]
License.title = "Accept license NOW!"
License.text = "Some boring stuff here..."
License.file_path = "samples/LICENSE"
# License.prefer_file = false

[vars]
var1 = "some path"
var2 = "false"
unused_var = "1"
cond1 = "false"
cond2 = "true"

[[action]]
type = "Copy"
var_source = "var1"
output_path = "~/.config/"
[[action]]
type = "Download"
var_source = "var2"
var_conds = [ "cond1", "cond2" ]
output_path = "~/.local/share/csi/"
